### ISSUE TITLE
Send alert to MUC?

### ISSUE THREAD

**Issue by poVoq** [trazfr/prometheus-xmpp-alerting#2]
Sometimes it is useful to send an alert to a group-chat. This seems to be not supported right now.

Thanks for looking into it.

**Comment by trazfr** [comment]
Hello,

I have just added the feature in https://github.com/trazfr/prometheus-xmpp-alerting/commit/2215e428a57137dd60c65dde0da8823e5c8d9936. You should just put in the config:

```json
"send_muc": [
    {
        "room": "monitoring-room-id@conference.example.com",
        "nick": "monitoring-bot"
    }
]
```

Regards

**Comment by poVoq** [comment]
Very cool! Thanks.
