### ISSUE TITLE
any hint on changing the timezone of .StartsAt

### ISSUE THREAD

**Issue by ian-kelling** [trazfr/prometheus-xmpp-alerting#3]
From the example config. It displays as UTC. The server OS's local time, or a hardcoded time zone both would work fine.

Thanks for working on this, I'm finding it very useful.

**Comment by trazfr** [comment]
Hello,

The timezone is currently the same as the one used by [Alertmanager](https://github.com/prometheus/alertmanager), as it uses the rfc3339. From my small tests, it seems to be only sending UTC as I only get startsAt / endsAt in the format `2023-11-29T20:21:23.456Z`.

However, it does sound legitimate to have a different timezone for alertmanager and its webhook.

**Comment by trazfr** [comment]
I have just pushed this commit: https://github.com/trazfr/prometheus-xmpp-alerting/commit/7e07e43b02ec23aa0e5025085bdd1ca1409fcc79

It should fix your issue by introducing a new `time_zone` parameter which can be:
- UTC (quite useless though given what alertmanager sends us)
- Local
- any timezone from the TZ db. For instance `Europe/Paris`

**Comment by ian-kelling** [comment]
Thank you! I'm using this and it is working.
